### ISSUE TITLE
About auto install

### ISSUE THREAD

**Issue by bobbywyx** [linsyking/vscode-joj-tools#2]
I felt lazy to install `JOJ-Submitter` and `JI-Auth`, so I just installed the extension. The issue is though the python packages are installed successfully they are not added to PATH. So the extension thinks that I didn't install the two packages. I think that manually installing the packages may be a better strategy. Or remind the user to add the python script library to PATH.
Environment:
win10 21H2
Python 3.10.5
vscode 1.72

**Comment by linsyking** [comment]
That's quite strange... Ji-auth and joj-submitter will add a script under PATH.
If you manually install the packages, will the command 'ji-auth' and 'joj-submit' work?

**Comment by linsyking** [comment]
What the extension does is exactly typing the "pip3 install ji-auth" to cmd.

**Comment by linsyking** [comment]
Or could you first check if "ji-auth.exe" and "joj-submit.exe" exist under your Python installation path/Scripts folder? (It's like `C:\Users\%Your Username%\AppData\Local\Programs\Python\Python38(Your python version)\Scripts`)

**Comment by bobbywyx** [comment]
Firstly, the `ji-auth.exe` is in the _Python installation path/Scripts folder_ , no matter by the auto installation or manual installation. Secondly, the _Python installation path/Scripts folder_ is not in PATH, but some scripts in it like `pip.exe` is in the PATH.

**Comment by bobbywyx** [comment]
Sorry I made a mistake. 
`pip3.exe` is in `C:\Program Files\Python310\Scripts\` and this catalog is in PATH.
But `ji-auth.exe` is in `C:\Users\myusername\AppData\Roaming\Python\Python310\Scripts`, which is not in PATH.

**Comment by linsyking** [comment]
> Sorry I made a mistake. 
> `pip3.exe` is in `C:\Program Files\Python310\Scripts\` and this catalog is in PATH.
> But `ji-auth.exe` is in `C:\Users\myusername\AppData\Roaming\Python\Python310\Scripts`, which is not in PATH.
> 

This is the problem of python installation. You should check your installation process.

**Comment by linsyking** [comment]
You can simply add the path to PATH to solve this problem.

**Comment by bobbywyx** [comment]
> You can simply add the path to PATH to solve this problem.

Yes, and I actually solved it at the beginning. I put this issue to mention the problem with PATH

**Comment by linsyking** [comment]
I will add this to Readme.
