### ISSUE TITLE
Check the version of JOJ-Submitter and JI-Auth with `--version` and upgrade them

### ISSUE THREAD

**Issue by BoYanZh** [linsyking/vscode-joj-tools#3]
Now both JOJ-Submitter and JI-Auth support `--version` option. You can check the version of them and use `pip3 install --upgrade <package-name>`  to upgrade them to the latest version.

**Comment by linsyking** [comment]
> Now both JOJ-Submitter and JI-Auth support `--version` option. You can check the version of them and use `pip3 install --upgrade <package-name>` to upgrade them to the latest version.

I tested your latest 0.0.5 version, It doesn't work anymore. seems you deleted my `--disable-mask` parameter. Thus I locked my ji-auth version to 0.0.3.

**Comment by BoYanZh** [comment]
Seems my hacking on `--version` has an unexpected side effect, fixed in 0.0.6.

**Comment by linsyking** [comment]
Seems don't need this feature now, closing
