### ISSUE TITLE
Captcha loading failed when "refreshing JOJ"

### ISSUE THREAD

**Issue by CHHC-L** [linsyking/vscode-joj-tools#5]
I installed joj-tools through VS Code Extension Market under joj-submit version 0.0.9 and ji-auth 0.0.6 . And then when I tried to refresh the status of JOJ in the tool, captcha failed to load.
It happens both with or without network system proxy.
The environment is Ubuntu 20.04 , Python 3.8.10 , VS Code 1.72.2 .

**Comment by linsyking** [comment]
can you first uninstall `joj-submit` and `ji-auth` and then run the extension again?

**Comment by CHHC-L** [comment]
> can you first uninstall `joj-submit` and `ji-auth` and then run the extension again?

Then after the extension showing "installing joj-submit / ji-auth ", it jumped to a captcha page in the VS Code and required captcha. This captcha still fails to load.

**Comment by linsyking** [comment]
paste the result of `ji-auth joj --help` here. (type it in your terminal)

**Comment by CHHC-L** [comment]
After totally re-install ji-auth, joj-submit and this tool and reset the proxy settings, it worked.
