### ISSUE TITLE
`JI-Auth` fails to run 

### ISSUE THREAD

**Issue by zhiyuan-251** [linsyking/vscode-joj-tools#6]
**Description**

`JI-Auth` Fail to run to render pixel art captcha, so the extension also fails in captcha without checking ID and password.

It says `Something wrong with captcha, username or password! Please try again by clicking the setting icon!`

**Environment**

* Extension Version: initial release
* JI-Auth Version: 0.0.7
* Terminal: Powershell (&WSL Ubuntu)
  
**Bug details**

![image](https://github.com/linsyking/vscode-joj-tools/assets/78415497/40456edf-8128-44f8-b5fa-c4ea80641bef)

```
Oops, Something went wrong. Please try again.
'ImageToAscii' object has no attribute 'image'
```

But on WSL where there is no conda, only async-timeout is installed by `sudo pip install ji-auth`, and the same exception also occurs.

**The suggestion/idea to fix it**

I want to see your env and maybe I can fix mine.

**Other info** 

This time the dependencies are installed by the extension automatically.

I've read [your PR here](https://github.com/BoYanZh/JI-Auth/pull/6) but I know little with async.

**Comment by linsyking** [comment]
I've also encountered this problem, it's related to captcha download bug in [this package](https://github.com/tc-imba/python-jaccount-cli). I will submit a PR to it.

**Comment by linsyking** [comment]
Have opened a [PR](https://github.com/tc-imba/python-jaccount-cli/pull/2)

**Comment by zhiyuan-251** [comment]
> Have opened a PR

When will this fix available to pip's source, after being merged? 

I think I have to wait some days to get the latest package and I don't know how to setup a package locally.

Also, I guess `pip` can run on my WSL.

**Comment by linsyking** [comment]
> > Have opened a PR
> 
> When will this fix available to pip's source, after being merged? 
> 
> I think I have to wait some days to get the latest package and I don't know how to setup a package locally.
> 
> Also, I guess `pip` can run on my WSL.

It depends on the author of that package. In case you need it now, follow that PR and edit it manually in your python site-packages.

**Comment by zhiyuan-251** [comment]
Works now after manually modifying the line. 👍 

Btw, how did you manage to locate the bug? I feel hard when the code involves in other packages. In lab we learned bisect method, but in fact we used print method…

**Comment by linsyking** [comment]
> Works now after manually modifying the line. 👍 
> 
> Btw, how did you manage to locate the bug? I feel hard when the code involves in other packages. In lab we learned bisect method, but in fact we used print method…

Python has error messages😉

**Comment by linsyking** [comment]
Keep this open until the upstream package updated.

**Comment by linsyking** [comment]
Fixed
